<form action="POST" method="post">
                <section class="container content-section ">
                    <h2 class="section-header">CART</h2>
                    <div class="cart-row">
                        <span class="cart-item cart-header cart-column">ITEM</span>
                        <span class="cart-price cart-header cart-column">PRICE</span>
                        <span class="cart-quantity cart-header cart-column">QUANTITY</span>
                    </div>
                    <div class="cart-items">
                        <div class="cart-row">
                            <div class="cart-item cart-column">
                                <img class="cart-item-image prodimg"  width="100" height="100">
                                <span class="cart-item-title product_title"></span>
                            </div>
                            <span class="cart-price cart-column product_price "></span>
                            <div class="cart-quantity cart-column">
                                <input class="cart-quantity-input" type="number" value="1">
                                <button class="btn btn-danger" type="button">REMOVE</button>
                            </div>
                        </div>
                        <!-- <div class="cart-row">
                            <div class="cart-item cart-column">
                                <img class="cart-item-image prodimg "  width="100" height="100">
                                <span class="cart-item-title product_title"></span>
                            </div>
                            <span class="cart-price cart-column product_price "> </span>
                            <div class="cart-quantity cart-column">
                                <input class="cart-quantity-input" type="number" value="1">
                                <button class="btn btn-danger" type="button">REMOVE</button>
                            </div>
                        </div> -->
                    </div>
                    <div class="cart-total">
                        <strong class="cart-total-title">Total</strong>
                        <span class="cart-total-price">$39.97</span>
                    </div>
                    <button class="btn btn-primary btn-purchase" type="button">PURCHASE</button>
                    </form>
                </section>