<?php $this->partial('layouts/frontend_header'); ?>
<!-- ##### Right Side Cart End ##### -->

<!-- ##### Single Product Details Area Start ##### -->
<section class="single_product_details_area d-flex align-items-center">

    <!-- Single Product Thumb -->

    <div class="single_product_thumb clearfix">
        <div class="product_thumbnail_slides owl-carousel ml-4 pl-4">
            <img src="../img/product/<?php echo json_decode($products['product_image'])[0];?>"
                style="height:500px; width:500px;">
            <img src="../img/product/<?php echo json_decode($products['product_image'])[1];?>"
                style="height:500px; width:500px;">
            <!-- <img src="img/product-img/product-big-3.jpg" alt=""> -->
        </div>
    </div>
    <!-- Single Product Description -->
    <div class="single_product_desc clearfix">
        <span>mango</span>
        <a href="cart.html">
            <h2><?php echo $products['title'];?></h2>
        </a>
        <p class="product-price"><span class="old-price">$65.00</span> <?php echo $products['prod_price']; ?></p>
        <p class="product-desc"><?php echo $products['prod_description'] ?></p>

        <!-- Form -->
        <form class="cart-form clearfix" method="post">
            <!-- Select Box -->
            <div class="select-box d-flex mt-50 mb-30">
                <select name="select" id="productSize" class="mr-5">
                    <option value="value">Size:<?php echo json_decode($products['size'])[0]; ?></option>
                    <option value="value">Size:<?php echo json_decode($products['size'])[1]; ?></option>
                    <option value="value">Size:<?php echo json_decode($products['size'])[2]; ?></option>
                    <option value="value">Size:<?php echo json_decode($products['size'])[3]; ?></option>
                </select>

            </div>
            <!-- Cart & Favourite Box -->
            <div class="cart-fav-box d-flex align-items-center">
                <!-- Cart -->
                <button type="submit" name="addtocart" class="btn essence-btn shop-item-button" 
                    data-id="<?php echo $products->prod_id; ?>">Add to cart</button>
                <!-- Favourite -->
                <div class="product-favourite ml-4">
                    <a href="#" class="favme fa fa-heart"></a>
                </div>
            </div>
        </form>
    </div>

</section>
<!-- ##### Single Product Details Area End ##### -->
<?php include __DIR__ . "/../layouts/script.phtml"; ?>
<!-- ##### Footer Area Start ##### -->
<?php $this->partial('layouts/frontend_footer'); ?>