<?php $this->partial("layouts/frontend_header"); ?>
<!-- ##### Header Area End ##### -->

<!-- //  include __DIR__ . "/../layouts/cart.phtml";  -->

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb_area bg-img" style="background-image: url(../asset/img/bg-img/breadcumb.jpg);">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12">
                <div class="page-title text-center">
                    <h2>dresses</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Breadcumb Area End ##### -->

<!-- ##### Shop Grid Area Start ##### -->
<section class="shop_grid_area section-padding-80">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-4 col-lg-3">
                <div class="shop_sidebar_area">

                    <!-- ##### Single Widget ##### -->
                    <div class="widget catagory mb-50">
                        <!-- Widget Title -->
                        <h6 class="widget-title mb-30">Catagories</h6>

                        <!--  Catagories  -->
                        <div class="catagories-menu">
                            <ul id="menu-content2" class="menu-content collapse show">
                                <!-- Single Item -->
                                <li data-toggle="collapse" data-target="#clothing">
                                    <a href="#">clothing</a>
                                    <ul class="sub-menu collapse show" id="clothing">
                                        <li><a href="#">All</a></li>
                                        <li><a href="#">Bodysuits</a></li>
                                        <li><a href="#">Dresses</a></li>
                                        <li><a href="#">Hoodies &amp; Sweats</a></li>
                                        <li><a href="#">Jackets &amp; Coats</a></li>
                                        <li><a href="#">Jeans</a></li>
                                        <li><a href="#">Pants &amp; Leggings</a></li>
                                        <li><a href="#">Rompers &amp; Jumpsuits</a></li>
                                        <li><a href="#">Shirts &amp; Blouses</a></li>
                                        <li><a href="#">Shirts</a></li>
                                        <li><a href="#">Sweaters &amp; Knits</a></li>
                                    </ul>
                                </li>
                                <!-- Single Item -->
                                <li data-toggle="collapse" data-target="#shoes" class="collapsed">
                                    <a href="#">shoes</a>
                                    <ul class="sub-menu collapse" id="shoes">
                                        <li><a href="#">All</a></li>
                                        <li><a href="#">Bodysuits</a></li>
                                        <li><a href="#">Dresses</a></li>
                                        <li><a href="#">Hoodies &amp; Sweats</a></li>
                                        <li><a href="#">Jackets &amp; Coats</a></li>
                                        <li><a href="#">Jeans</a></li>
                                        <li><a href="#">Pants &amp; Leggings</a></li>
                                        <li><a href="#">Rompers &amp; Jumpsuits</a></li>
                                        <li><a href="#">Shirts &amp; Blouses</a></li>
                                        <li><a href="#">Shirts</a></li>
                                        <li><a href="#">Sweaters &amp; Knits</a></li>
                                    </ul>
                                </li>
                                <!-- Single Item -->
                                <li data-toggle="collapse" data-target="#accessories" class="collapsed">
                                    <a href="#">accessories</a>
                                    <ul class="sub-menu collapse" id="accessories">
                                        <li><a href="#">All</a></li>
                                        <li><a href="#">Bodysuits</a></li>
                                        <li><a href="#">Dresses</a></li>
                                        <li><a href="#">Hoodies &amp; Sweats</a></li>
                                        <li><a href="#">Jackets &amp; Coats</a></li>
                                        <li><a href="#">Jeans</a></li>
                                        <li><a href="#">Pants &amp; Leggings</a></li>
                                        <li><a href="#">Rompers &amp; Jumpsuits</a></li>
                                        <li><a href="#">Shirts &amp; Blouses</a></li>
                                        <li><a href="#">Shirts</a></li>
                                        <li><a href="#">Sweaters &amp; Knits</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <!-- ##### Single Widget ##### -->
                    <div class="widget price mb-50">
                        <!-- Widget Title -->
                        <h6 class="widget-title mb-30">Filter by</h6>
                        <!-- Widget Title 2 -->
                        <p class="widget-title2 mb-30">Price</p>

                        <div class="widget-desc">
                            <div class="slider-range">
                                <div data-min="49" data-max="360" data-unit="$"
                                    class="slider-range-price ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all"
                                    data-value-min="49" data-value-max="360" data-label-result="Range:">
                                    <div class="ui-slider-range ui-widget-header ui-corner-all"></div>
                                    <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                                    <span class="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"></span>
                                </div>
                                <div class="range-price">Range: $49.00 - $360.00</div>
                            </div>
                        </div>
                    </div>

                    <!-- ##### Single Widget ##### -->
                    <div class="widget color mb-50">
                        <!-- Widget Title 2 -->
                        <p class="widget-title2 mb-30">Color</p>
                        <div class="widget-desc">
                            <ul class="d-flex">
                                <li><a href="#" class="color1"></a></li>
                                <li><a href="#" class="color2"></a></li>
                                <li><a href="#" class="color3"></a></li>
                                <li><a href="#" class="color4"></a></li>
                                <li><a href="#" class="color5"></a></li>
                                <li><a href="#" class="color6"></a></li>
                                <li><a href="#" class="color7"></a></li>
                                <li><a href="#" class="color8"></a></li>
                                <li><a href="#" class="color9"></a></li>
                                <li><a href="#" class="color10"></a></li>
                            </ul>
                        </div>
                    </div>

                    <!-- ##### Single Widget ##### -->
                    <div class="widget brands mb-50">
                        <!-- Widget Title 2 -->
                        <p class="widget-title2 mb-30">Brands</p>
                        <div class="widget-desc">
                            <ul>
                                <li><a href="#">Asos</a></li>
                                <li><a href="#">Mango</a></li>
                                <li><a href="#">River Island</a></li>
                                <li><a href="#">Topshop</a></li>
                                <li><a href="#">Zara</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-8 col-lg-9">
                <div class="shop_grid_product_area">
                    <div class="row">
                        <div class="col-12">
                            <div class="product-topbar d-flex align-items-center justify-content-between">
                                <!-- Total Products -->
                                <div class="total-products">
                                    <p><span>186</span> products found</p>
                                </div>
                                <!-- Sorting -->
                                <div class="product-sorting d-flex">
                                    <p>Sort by:</p>
                                    <form action="#" method="get">
                                        <select name="select" id="sortByselect">
                                            <option value="value">Highest Rated</option>
                                            <option value="value">Newest</option>
                                            <option value="value">Price: $$ - $</option>
                                            <option value="value">Price: $ - $$</option>
                                        </select>
                                        <input type="submit" class="d-none" value="">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>



                    <div class="row">
                        <!-- Single Product -->
                        <?php foreach ($product as $products) { ?>
                        <div class="col-12 col-sm-6 col-lg-4 shop-item ">
                            <div class="single-product-wrapper">
                                <!-- Product Image -->
                                <div class="product-img">
                                    <img src="../img/product/<?php echo json_decode($products->product_image)[0]; ?>"
                                        alt="" style="height:300px !important">
                                    <!-- Hover Thumb -->
                                    <img class="hover-img"
                                        src="../img/product/<?php echo json_decode($products->product_image)[1]; ?>"
                                        alt="" style="height:300px !important;">

                                    <!-- Product Badge -->
                                    <div class="product-badge offer-badge">
                                        <span></span>
                                    </div>
                                    <!-- Favourite -->
                                    <div class="product-favourite">
                                        <a href="#" class="favme fa fa-heart"></a>
                                    </div>
                                </div>

                                <!-- Product Description -->
                                <div class="product-description">
                                    <span>Pl's</span>
                                    <a href="detail">
                                        <h6>
                                            <?php echo $products->title; ?>
                                        </h6>
                                    </a>
                                    <p class="product-price"><span class="old-price">$75.00</span>
                                        <?php echo $products->prod_price; ?>
                                    </p>

                                    <!-- Hover Content -->
                                    <div class="hover-content">
                                        <!-- Add to Cart -->
                                        <div id="div1" class="add-to-cart-btn">
                                            <!-- <a href="#" class="btn essence-btn">Add to Cart</a> -->
                                            <button type="submit" id="addtocart"
                                                class="btn essence-btn shop-item-button"
                                                data-id="<?php echo $products->prod_id; ?>">Add To Cart
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php } ?>
                        <!-- Pagination -->
                        <nav aria-label="navigation">
                            <ul class="pagination mt-50 mb-70">
                                <!-- <li class="page-item"><a class="page-link" href="#"> -->
                                <!-- <i class="fa fa-angle-left"></i></a></li> -->
                                <li class="page-item"><a class="page-link" href="">Prev</a></li>
                                <!-- <li class="page-item"><a class="page-link" href="#">...</a></li> -->
                                <li class="page-item"><a class="page-link" href="#">Next</a></li>
                                <!-- <li class="page-item"><a class="page-link" href="#"> -->
                                <!-- <i class="fa fa-angle-right"></i></a></li> -->
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
</section>

<!-- ##### Shop Grid Area End ##### -->

<!-- ##### Footer Area Start ##### -->
<footer class="footer_area clearfix">
    <div class="container">
        <div class="row">
            <!-- Single Widget Area -->
            <div class="col-12 col-md-6">
                <div class="single_widget_area d-flex mb-30">
                    <!-- Logo -->
                    <div class="footer-logo mr-50">
                        <a href="#"><img src="../asset/img/core-img/logo2.png" alt=""></a>
                    </div>
                    <!-- Footer Menu -->
                    <div class="footer_menu">
                        <ul>
                            <li><a href="shop.html">Shop</a></li>
                            <li><a href="blog.html">Blog</a></li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-md-6">
                <div class="single_widget_area mb-30">
                    <ul class="footer_widget_menu">
                        <li><a href="#">Order Status</a></li>
                        <li><a href="#">Payment Options</a></li>
                        <li><a href="#">Shipping and Delivery</a></li>
                        <li><a href="#">Guides</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="#">Terms of Use</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row align-items-end">
            <!-- Single Widget Area -->
            <div class="col-12 col-md-6">
                <div class="single_widget_area">
                    <div class="footer_heading mb-30">
                        <h6>Subscribe</h6>
                    </div>
                    <div class="subscribtion_form">
                        <form action="#" method="post">
                            <input type="email" name="mail" class="mail" placeholder="Your email here">
                            <button type="button" class="submit"><i class="fa fa-long-arrow-right"
                                    aria-hidden="true"></i></button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Single Widget Area -->
            <div class="col-12 col-md-6">
                <div class="single_widget_area">
                    <div class="footer_social_area">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><i
                                class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><i
                                class="fa fa-instagram" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><i class="fa fa-twitter"
                                aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Pinterest"><i
                                class="fa fa-pinterest" aria-hidden="true"></i></a>
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Youtube"><i
                                class="fa fa-youtube-play" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row mt-5">
            <div class="col-md-12 text-center">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>
                    document.write(new Date().getFullYear());
                    </script> All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by
                    <a href="https://colorlib.com" target="_blank">Colorlib</a>, distributed by <a
                        href="https://themewagon.com/" target="_blank">ThemeWagon</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>

    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
    $(document).ready(function() {
        window.onbeforeunload = function() {
            return "Do you really want to close?";
        };
        // window.sessionStorage.setItem("carts", null);
        var htmls = '';
        $(".shop-item-button").click(function(e) {
            var prod_id = $(this).data('id');
            $.ajax({
                url: "cart",
                type: "GET",
                data: {
                    "prod_id": prod_id
                },
                success: function(result) {
                    img = JSON.parse(result.product_image)[0];
                    testArray = [prod_id, img, result.title, result.prod_price]
                    sess_data = JSON.parse(sessionStorage.getItem("carts")) || [];
                    JSON.stringify(sess_data)
                    flag = 0;
                    for (i = 0; i < sess_data.length; i++) {
                        if (sess_data[i][0] == testArray[0]) {
                            flag = 1;
                        }
                    }
                    if (flag == 0) {

                        sess_data.push(testArray)
                        sessionStorage.setItem("carts", JSON.stringify(sess_data))
                        loadCart();
                    }
                    // $('#cartModal').modal('toggle')
                }
            });
        });
    });

    $('#cartModal').on('hide.bs.modal', function() {
        $('div .cart-items').empty()
    });

    $('#essenceCartBtn').click(function() {

    })
    loadCart()

    function loadCart() {
        var htmls = '';
        newdata = JSON.parse(sessionStorage.getItem("carts"))
        JSON.stringify(newdata)
        count = newdata.length
        $('.hen').text(count);
        for (k = 0; k < newdata.length; k++) {
            htmls += '<div class="cart-row">';
            htmls += '<div class="cart-item cart-column">';
            htmls += '<img class="cart-item-image prodimg" src="../img/product/' + newdata[k][1] +
                '" width="100" height="100">'
            htmls += '<span class="cart-item-title product_title">' + newdata[k][2] + '</span>';
            htmls += '</div>';
            htmls += '<span class="cart-price cart-column product_price ">' + newdata[k][3] + '</span>';
            htmls += '<div class="cart-quantity cart-column">';
            htmls += '<input class="cart-quantity-input" type="number" value="1">';
            htmls += '<button class="btn btn-danger removeCart" data-id="' + newdata[k][0] +
                '" type="button">REMOVE</button>';
            htmls += '</div></div>';
            $('.cart-items').html(htmls);
        }
    }
    </script>

    <script>
    $(document).ready(function() {
        $('#addtocart').on('click', function() {

            var button = $(this);
            var cart = $('#div1');
            var cartTotal = cart.attr('data-totalitems');
            var newCartTotal = parseInt(cartTotal) + 1;

            button.addClass('sendtocart');
            setTimeout(function() {
                button.removeClass('sendtocart');
                cart.addClass('shake').attr('data-totalitems', newCartTotal);
                setTimeout(function() {
                    cart.removeClass('shake');
                }, 500)
            }, 1000)
        })
    })
    </script>

</footer>
<!-- ##### Footer Area End ##### -->

<!-- jQuery (Necessary for All JavaScript Plugins) -->
<script src="../asset/js/jquery/jquery-2.2.4.min.js"></script>
<!-- Popper js -->
<script src="../asset/js/popper.min.js"></script>
<!-- Bootstrap js -->
<script src="../asset/js/bootstrap.min.js"></script>
<!-- Plugins js -->
<script src="../asset/js/plugins.js"></script>
<!-- Classy Nav js -->
<script src="../asset/js/classy-nav.min.js"></script>
<!-- Active js -->
<script src="../asset/js/active.js"></script>

</body>

</html>