<?php $this->partial('layouts/header'); ?>

<div class="card-body">
    <h4 class="card-title">Product Form</h4>
    <p class="card-description">
        Add Product
    </p>
    <form action='product/create' method="post" enctype="multipart/form-data" class="forms-sample">
        <div class="form-group">
            <label for="exampleInputName1">Brand</label>
            <input type="text" class="form-control" id="brand" placeholder="Brand">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail3">Title</label>
            <input type="text" class="form-control" id="title" placeholder="Email">
        </div>
        <!-- Checkbox for size -->
        <div>
            <label for="size">Size</label>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox1" value="option1">
                <label class="form-check-label" for="inlineCheckbox1">S</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox2" value="option2">
                <label class="form-check-label" for="inlineCheckbox2">M</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox3" value="option3">
                <label class="form-check-label" for="inlineCheckbox3">L</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox4" value="option4">
                <label class="form-check-label" for="inlineCheckbox4">XL</label>
            </div>
            <div class="form-check form-check-inline">
                <input class="form-check-input" type="checkbox" id="inlineCheckbox5" value="option5">
                <label class="form-check-label" for="inlineCheckbox5">XXL</label>
            </div>
        </div>
        <!-- onchange="readURL(this,1)" -->
        <!-- End of Checkbox -->
        <div class="form-group">
            <label for="files">Select multiple files</label>
            <input id="files" type="file" multiple="multiple">
            <output id="previewImg">
        </div>
        </div>
    
        <!-- <div class="card-body">
            <div class="col" id="preview_image">
                <img src="#" id="previewImg" alt="Insert Image" style="width: 40%; height:auto;">
                <img src="#" id="previewImg1" alt="Insert Image" style="width: 40%; height:auto;">
            </div>
        </div> -->


<div class="input-group mb-4">
    <label for="price" class="">Prize</label>
    <div class="input-group-prepend">
        <span class="input-group-text bg-primary text-white">Rs.</span>
    </div>
    <input type="text" class="form-control" id="product_prize" aria-label="Amount (to the nearest ruppes)">
    <div class="input-group-append">
        <span class="input-group-text">.00</span>
    </div>
</div>

<div class="form-group">
    <label for="productDescription">Product Description</label>
    <textarea id="wmd-input" name="post-text" class="form-control-lg" data-editor-type="wmd" cols="80" rows="10"
        tabindex="101"></textarea>
</div>

<button type="submit" class="btn btn-primary me-2">Submit</button>
<button class="btn btn-light">Cancel</button>

</form>
</div>
</div>

<style>
#previewImg {
    display: flex;
    gap: 10px;
    padding: 10px 0;
}

.thumbnail {
    height: 50px;
    width: 50px;
}
</style>

<script>
document.querySelector("#files").addEventListener("change", (e) => {
    if (window.File && window.FileReader && window.FileList && window.Blob) {
        const files = e.target.files;
        const output = document.querySelector("#previewImg");
        output.innerHTML = "";
        for (let i = 0; i < files.length; i++) {
            if (!files[i].type.match("image")) continue;
            const picReader = new FileReader();
            picReader.addEventListener("load", function(event) {
                const picFile = event.target;
                const div = document.createElement("div");
                div.innerHTML =
                    `<img class="thumbnail" src="${picFile.result}" title="${picFile.name}"/>`;
                output.appendChild(div);
            });
            picReader.readAsDataURL(files[i]);
        }
    } else {
        alert("Your browser does not support File API");
    }
});

</script>



<?php $this->partial('layouts/footer'); ?>