<?php $this->partial('layouts/header');?>


<div class="card-body col-md-12" style="overflow-x:scroll;">
    <table class="table">
        <thead>
            <tr>
                <th>Product ID</th>
                <th>Product Image</th>
                <th>Title</th>
                <th>Brand</th>
                <th>Category</th>
                <th>Price</th>
                <th>Size</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody >
            <?php foreach ($prod as $p ) { ?>

                <tr>
                    <td> <?php echo $p['prod_id']; ?></td>
                    <td id="files"> 
                        <?php 
                            $img =  json_decode($p['product_image']); 
                            foreach($img as $image){
                                echo $image.',';
                            }
                        ?>
                        <output id="previewImg">
                    </td>
                    <td> <?php echo $p['title']; ?></td>
                    <td> <?php echo $p['brand']; ?></td>
                    <td> <?php echo $p['cat_id']; ?></td>
                    <td> <?php echo $p['prod_price']; ?></td>
                    <td style="display:flex; margin-top:28px;"> 
                        <?php 
                            $s = json_decode($p['size']); 
                            foreach($s as $size){
                                echo '<span class="badge badge-info">'.$size.'</span>';
                            }
                        ?>
                    </td>
                    <td >
                        <button class="btn btn-xs btn-primary">Edit</button>
                        <button class="btn btn-xs btn-danger">Delete</button>
                    </td>
                </tr>
            <?php }?>
        </tbody>
    </table>
</div>

<script>
document.querySelector("#files").addEventListener("change", (e) => {
    if (window.File && window.FileReader && window.FileList && window.Blob) {
        const files = e.target.files;
        const output = document.querySelector("#previewImg");
        output.innerHTML = "";
        for (let i = 0; i < files.length; i++) {
            if (!files[i].type.match("image")) continue;
            const picReader = new FileReader();
            picReader.addEventListener("load", function(event) {
                const picFile = event.target;
                const div = document.createElement("div");
                div.innerHTML =
                    `<img class="thumbnail" src="${picFile.result}" title="${picFile.name}"/>`;
                output.appendChild(div);
            });
            picReader.readAsDataURL(files[i]);
        }
    } else {
        alert("Your browser does not support File API");
    }
});
</script>


<?php $this->partial('layouts/footer');?>