
<!-- Form starts from here -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
<div class="d-flex justify-content-center mt-5">
<form action="user/login" method="post">
    <h3 class="card-header text-center" >Login</h3>
  <!-- Email input -->
  <div class="form-outline mb-4">
    <input type="text" id="username" name="username" class="form-control" />
    <label class="form-label" for="name">Email address</label>
  </div>
  <!-- Password input -->
  <div class="form-outline mb-4">
    <input type="text" id="password" name="password" class="form-control" />
    <label class="form-label" for="pass">Password</label>
  </div>
  <!-- Submit button -->
  <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
</form>
</div>
</body>
</html>