
<!-- Form starts from here -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
</head>

<body>
<div class="d-flex justify-content-center mt-5">
<form action="signin/doSignin" method="post">
    <h3 class="card-header text-center" >Login</h3>
  <!-- Email input -->
  <div class="form-outline mb-4">
  <?php echo $this->flashSession->output(); ?>

    <input type="text" id="username" name="email" class="form-control" />
    <label class="form-label" for="email">Email address</label>
  </div>
  <!-- Password input -->
  <div class="form-outline mb-4">
    <input type="text" id="password" name="password" class="form-control" />
    <label class="form-label" for="password">Password</label>
  </div>
  <!-- Submit button -->
  <button type="submit" id="save" value="signin" class="btn btn-primary btn-block mb-4">Sign in</button>
</form>
</div>
</body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
  
  setTimeout(function(){
    $('.alert').hide();
  }, 3000);



  // $('#save').click(function() {
  //                   var email = $('#email').val();
  //                   var password = $('#password').val();
  //                   $.ajax({
  //                       url: "signin/doSignin",
  //                       type: "POST",
  //                       dataType: 'json',
  //                       data: {
  //                           email,
  //                           password
  //                       },
  //                       success: function(response) {
  //                           console.log(response);
  //                           $('#details').modal('hide');
  //                           $('#successMessage').html(response);
  //                           $('#successMessage').show();
  //                           location.reload();
  //                       },
  //                   });
  //               });
  </script>
</html>