<script>
    $(document).ready(function() {
        window.onbeforeunload = function() {
            return "Do you really want to close?";
        };
        // window.sessionStorage.setItem("carts", null);
        var htmls = '';
        $(".shop-item-button").click(function(e) {
            var prod_id = $(this).data('id');
            $.ajax({
                url: "cart",
                type: "GET",
                data: {
                    "prod_id": prod_id
                },
                success: function(result) {
                    img = JSON.parse(result.product_image)[0];
                    testArray = [prod_id, img, result.title, result.prod_price]
                    sess_data = JSON.parse(sessionStorage.getItem("carts")) || [];
                    JSON.stringify(sess_data)
                    flag = 0;
                    for (i = 0; i < sess_data.length; i++) {
                        if (sess_data[i][0] == testArray[0]) {
                            flag = 1;
                        }
                    }
                    if (flag == 0) {

                        sess_data.push(testArray)
                        sessionStorage.setItem("carts", JSON.stringify(sess_data))
                        loadCart();
                    }
                    // $('#cartModal').modal('toggle')
                }
            });
        });
    });

    $('#cartModal').on('hide.bs.modal', function() {
        $('div .cart-items').empty()
    });

    $('#essenceCartBtn').click(function() {

    })
    loadCart()

    function loadCart() {
        var htmls = '';
        newdata = JSON.parse(sessionStorage.getItem("carts"))
        JSON.stringify(newdata)
        count = newdata.length
        $('.hen').text(count);
        for (k = 0; k < newdata.length; k++) {
            htmls += '<div class="cart-row">';
            htmls += '<div class="cart-item cart-column">';
            htmls += '<img class="cart-item-image prodimg" src="../img/product/' + newdata[k][1] +
                '" width="100" height="100">'
            htmls += '<span class="cart-item-title product_title">' + newdata[k][2] + '</span>';
            htmls += '</div>';
            htmls += '<span class="cart-price cart-column product_price ">' + newdata[k][3] + '</span>';
            htmls += '<div class="cart-quantity cart-column">';
            htmls += '<input class="cart-quantity-input" type="number" value="1">';
            htmls += '<button class="btn btn-danger removeCart" data-id="' + newdata[k][0] +
                '" type="button">REMOVE</button>';
            htmls += '</div></div>';
            $('.cart-items').html(htmls);
        }
    }
    </script>

    <script>
    $(document).ready(function() {
        $('#addtocart').on('click', function() {

            var button = $(this);
            var cart = $('#div1');
            var cartTotal = cart.attr('data-totalitems');
            var newCartTotal = parseInt(cartTotal) + 1;

            button.addClass('sendtocart');
            setTimeout(function() {
                button.removeClass('sendtocart');
                cart.addClass('shake').attr('data-totalitems', newCartTotal);
                setTimeout(function() {
                    cart.removeClass('shake');
                }, 500)
            }, 1000)
        })
    })
    </script>